// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VizeWeb.DatabaseContext2;

namespace VizeWeb.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20211128131937_BasvurularEklendi")]
    partial class BasvurularEklendi
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VizeWeb.Models.Basvuru", b =>
                {
                    b.Property<int>("YarismaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BasvuruTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("TakimID")
                        .HasColumnType("int");

                    b.Property<string>("YarismaName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("YarismaID");

                    b.HasIndex("TakimID");

                    b.ToTable("Basvurular");
                });

            modelBuilder.Entity("VizeWeb.Models.Duyuru", b =>
                {
                    b.Property<int>("DuyuruID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DuyuruAciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DuyuruBaslik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DuyuruDetayLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DuyuruTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("DuyuruID");

                    b.ToTable("Duyurular");
                });

            modelBuilder.Entity("VizeWeb.Models.Takim", b =>
                {
                    b.Property<int>("TakimdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TakimUyeSayisi")
                        .HasColumnType("int");

                    b.HasKey("TakimdId");

                    b.ToTable("Takimlar");
                });

            modelBuilder.Entity("VizeWeb.Models.Uye", b =>
                {
                    b.Property<int>("UyeOkulNo")
                        .HasColumnType("int");

                    b.Property<int?>("TakimID")
                        .HasColumnType("int");

                    b.Property<string>("UyeAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UyeAlan")
                        .HasColumnType("int");

                    b.Property<DateTime>("UyeDogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("UyeMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UyeTelNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UyeOkulNo");

                    b.HasIndex("TakimID");

                    b.ToTable("Uyeler");
                });

            modelBuilder.Entity("VizeWeb.Models.Basvuru", b =>
                {
                    b.HasOne("VizeWeb.Models.Takim", "BasvuranTakim")
                        .WithMany("Yarismalar")
                        .HasForeignKey("TakimID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BasvuranTakim");
                });

            modelBuilder.Entity("VizeWeb.Models.Uye", b =>
                {
                    b.HasOne("VizeWeb.Models.Takim", "UyeTakim")
                        .WithMany("TakimUyeleri")
                        .HasForeignKey("TakimID");

                    b.Navigation("UyeTakim");
                });

            modelBuilder.Entity("VizeWeb.Models.Takim", b =>
                {
                    b.Navigation("TakimUyeleri");

                    b.Navigation("Yarismalar");
                });
#pragma warning restore 612, 618
        }
    }
}
